apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: postgres
  namespace: kube-system
spec:
  serviceName: "postgres"
  replicas: 1
  volumeClaimTemplates:
  - metadata:
      name: db
      annotations:
        volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
  template:
    metadata:
      labels:
        software: apache
        project: postgresql
        app: postgres
        version: v1
        name: postgres
    spec:
      serviceAccount: nfs-provisioner
      nodeSelector:
        type: backEndNode1
      containers:
      - name: postgres 
        image: postgres:10.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db
          mountPath: /var/lib/postgersql/data
        env:
            - name: POSTGRES_USER
              value: "user_name"
            - name: POSTGRES_PASSWORD
              value: "password"
