apiVersion: v1 
kind: Service 
metadata: 
  name: postgres 
  labels: 
    name: postgres
spec:
  type: NodePort
  ports: 
  - port: 5432 
    targetPort: 5432
    nodePort: 30002
  selector:
    name: postgres 